# Generated by Django 2.0.6 on 2018-06-12 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kamigurumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('size', models.FloatField()),
                ('sold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamigurumi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='KamigurumiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(unique=True, upload_to='')),
                ('kamigurumi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='kamigurumi.Kamigurumi')),
            ],
        ),
    ]
